/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerData {
  'unlockedBackgrounds' : Array<bigint>,
  'equippedBackground' : bigint,
  'coins' : bigint,
  'unlockedCubeStyles' : Array<bigint>,
  'equippedCubeStyle' : bigint,
  'playerName' : string,
  'lastDailyClaim' : bigint,
}
export interface ScoreEntry {
  'score' : bigint,
  'timestamp' : bigint,
  'playerName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardGameCoins' : ActorMethod<[bigint], bigint>,
  'claimDailyReward' : ActorMethod<[], bigint>,
  'equipBackground' : ActorMethod<[bigint], undefined>,
  'equipCubeStyle' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerData' : ActorMethod<[], PlayerData>,
  'getTopScores' : ActorMethod<[], Array<ScoreEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitScore' : ActorMethod<[bigint, string], undefined>,
  'unlockBackground' : ActorMethod<[bigint], undefined>,
  'unlockCubeStyle' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];