/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ThemeId = IDL.Nat;
export const SkinId = IDL.Nat;
export const PlayerData = IDL.Record({
  'coins' : IDL.Nat,
  'unlockedThemes' : IDL.Vec(ThemeId),
  'playerName' : IDL.Text,
  'lastDailyClaim' : IDL.Int,
  'unlockedSkins' : IDL.Vec(SkinId),
});
export const Timestamp = IDL.Int;
export const ScoreEntry = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unlockSkin' : IDL.Func([SkinId], [], []),
  'unlockTheme' : IDL.Func([ThemeId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ThemeId = IDL.Nat;
  const SkinId = IDL.Nat;
  const PlayerData = IDL.Record({
    'coins' : IDL.Nat,
    'unlockedThemes' : IDL.Vec(ThemeId),
    'playerName' : IDL.Text,
    'lastDailyClaim' : IDL.Int,
    'unlockedSkins' : IDL.Vec(SkinId),
  });
  const Timestamp = IDL.Int;
  const ScoreEntry = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unlockSkin' : IDL.Func([SkinId], [], []),
    'unlockTheme' : IDL.Func([ThemeId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };