/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerData {
  'coins' : bigint,
  'unlockedThemes' : Array<ThemeId>,
  'playerName' : string,
  'lastDailyClaim' : bigint,
  'unlockedSkins' : Array<SkinId>,
}
export interface ScoreEntry {
  'score' : bigint,
  'timestamp' : Timestamp,
  'playerName' : string,
}
export type SkinId = bigint;
export type ThemeId = bigint;
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyReward' : ActorMethod<[], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPlayerData' : ActorMethod<[], PlayerData>,
  'getTopScores' : ActorMethod<[], Array<ScoreEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitScore' : ActorMethod<[bigint, string], undefined>,
  'unlockSkin' : ActorMethod<[SkinId], undefined>,
  'unlockTheme' : ActorMethod<[ThemeId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];