/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlayerData = IDL.Record({
  'unlockedBackgrounds' : IDL.Vec(IDL.Nat),
  'equippedBackground' : IDL.Nat,
  'coins' : IDL.Nat,
  'unlockedCubeStyles' : IDL.Vec(IDL.Nat),
  'equippedCubeStyle' : IDL.Nat,
  'playerName' : IDL.Text,
  'lastDailyClaim' : IDL.Int,
});
export const ScoreEntry = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardGameCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
  'equipBackground' : IDL.Func([IDL.Nat], [], []),
  'equipCubeStyle' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unlockBackground' : IDL.Func([IDL.Nat], [], []),
  'unlockCubeStyle' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlayerData = IDL.Record({
    'unlockedBackgrounds' : IDL.Vec(IDL.Nat),
    'equippedBackground' : IDL.Nat,
    'coins' : IDL.Nat,
    'unlockedCubeStyles' : IDL.Vec(IDL.Nat),
    'equippedCubeStyle' : IDL.Nat,
    'playerName' : IDL.Text,
    'lastDailyClaim' : IDL.Int,
  });
  const ScoreEntry = IDL.Record({
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardGameCoins' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'claimDailyReward' : IDL.Func([], [IDL.Nat], []),
    'equipBackground' : IDL.Func([IDL.Nat], [], []),
    'equipCubeStyle' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlayerData' : IDL.Func([], [PlayerData], ['query']),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitScore' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unlockBackground' : IDL.Func([IDL.Nat], [], []),
    'unlockCubeStyle' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };